version: '3.8'

services:
  php:
    container_name: symfony_php
    build:
      context: ./api
      dockerfile: ../docker/Dockerfile.php
    volumes:
      - ./api:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db

  nginx:
    container_name: symfony_nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    container_name: symfony_db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: altman_db
      MYSQL_USER: altman
      MYSQL_PASSWORD: altmanpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  front:
    container_name: react_front
    build:
      context: ./front
      dockerfile: ../docker/Dockerfile.front
    volumes:
      - ./front:/app
    ports:
      - "5173:5173"
    working_dir: /app
    #command: npm run dev

volumes:
  db_data: